export const termsOfUseCopy: string[] = [
  "Introduction",
  "By applying for or using Transaction Junction (\"TJ\") services, you agree to the following Terms of Use.",
  "In this document, \"you\" refers to your business and any associated affiliates.",
  "Transaction Junction offers several solutions. These Terms of Use apply to all services, but you are only responsible for paying for the solutions you have specifically requested and that TJ has activated for you.",
  "If there is any conflict between these Terms of Use and a separate signed agreement between the parties, the terms of the signed agreement will apply",
  "1. General Terms",
  "These terms apply to all TJ services you use.",
  "Your Responsibilities",
  "Use the TJ online portal to view transaction details and investigate issues before logging a support request.",
  "Safeguard all credentials, passwords, API keys, and portal access details shared with you by TJ, as you will be responsible for unauthorised access using your secret credentials.",
  "Report any suspected fraud or system issues to TJ as soon as you become aware of them.",
  "Follow TJ's processes for submitting support requests, incident reporting, and change management.",
  "Manage transaction disputes directly with your acquiring bank or other payment partners.",
  "Ensure that version or configuration updates to your POS software or network do not disrupt your connection to TJ services.",
  "Maintain network connectivity that meets TJ's technical specifications.",
  "Whenever you request TJ to make a configuration change that may affect the services we provide, it is your responsibility to validate that the change has been made correctly, including confirming that settlement is occurring as expected.",
  "Transaction Junction's Responsibilities",
  "Provide you with access to the TJ platform and relevant tools such as the online portal or APIs.",
  "Maintain a PCI-DSS Level One certified and compliant solution.",
  "Ensure market-acceptable system availability across all platforms.",
  "Assist with end-to-end testing to confirm integrations and ensure services are functioning correctly where required.",
  "Maintain a documented and tested disaster recovery and failover plan.",
  "Operate both business-hours and after-hours support for critical issues (defined as P1 issues in our issue prioritisation table).",
  "Protect your data and share it only with authorized representatives or third parties as required to provide services or facilitate settlement.",
  "Definitions:",
  "Effective Date: The date on which TJ services go live and are available for your use.",
  "Parties: Refers to both you (the Client) and Transaction Junction (the Service Provider).",
  "Liability: any loss, damage, costs, fines, penalties and/or claims suffered by or incurred by a Party.",
  "2. Term, Suspension and Termination",
  "The minimum term for using TJ services is 12 months from the date your first service is activated. The minimum term is calculated per service.",
  "After the minimum term for a service is reached, the service and the terms will remain in place until either party gives 60 days' written notice of termination.",
  "During the notice period, TJ will continue to provide services, and you will remain responsible for paying all applicable fees.",
  "Any unpaid fees for services already rendered remain due even after termination.",
  "Should fees due to TJ be unpaid, TJ will attempt to contact you to prompt for payment. TJ has the right to suspend services until payment has been made or a payment plan has been agreed.",
  "3. Support Services",
  "Your Responsibilities",
  "Submit support queries to support@switch.tj with as much detail as possible (including context, issue description, and desired outcome).",
  "Join the relevant WhatsApp system notification channels for real-time updates for system-wide issues.",
  "Transaction Junction's Responsibilities",
  "Provide operational and technical support during business hours.",
  "Provide after-hours support for critical issues.",
  "4. In-Person Integrated Payment Services",
  "Transaction Junction's Responsibilities",
  "Process your transactions through integrated payment channels.",
  "Monitor platform connections to payment providers (e.g., banks and alternative payment methods).",
  "Store transaction data securely for at least five (5) years.",
  "Provide an online portal for near real-time access to your transactional data.",
  "Share transactional data only with you and your authorized representatives.",
  "Maintain a Point-to-Point-Encryption listed solution unless confirmed otherwise in writing.",
  "Your Responsibilities",
  "Direct any settlement or payment queries to your payment providers if TJ is not the settling party.",
  "Allow TJ to share your details with third parties as needed to process or settle funds.",
  "Support TJ in performing remote testing (e.g., via screen-sharing) when required.",
  "5. eCommerce Services",
  "Transaction Junction's Responsibilities",
  "Maintain an ecommerce platform that you can access and use.",
  "Provide you with the required secret credentials to TJ's eCommerce platform and related features.",
  "Process payments and authentication based on your requirements.",
  "Support end-to-end testing with relevant payment providers as needed.",
  "Your Responsibilities",
  "Use the merchant portal to view and investigate transactions.",
  "Permit TJ to engage with third parties as needed for settlement purposes.",
  "6. Reconciliation Services",
  "Transaction Junction's Responsibilities",
  "Process daily transaction files from relevant 3rd parties and perform automated reconciliation.",
  "Display consolidated reconciliation results on the TJ web dashboard.",
  "Store reconciliation data for at least 90 days.",
  "Your Responsibilities",
  "Where daily transactional data is not received from 3rd parties by Transaction Junction, escalate to your payment partners to prompt for the delivery of required data to TJ to perform your reconciliation.",
  "7. Professional Services",
  "Professional services relate to analysis, testing, software development and consultancy services which may be requested by you from time to time.",
  "Transaction Junction's Responsibilities",
  "Only perform professional services where you have explicitly agreed to the associated fees.",
  "Provide a defined scope of work and cost estimate for any work prior to initiation.",
  "Your Responsibilities",
  "Settle the fees associated with professional services as per the agreement in writing, which may differ from these terms of use.",
  "7. Additional Services",
  "If you wish to activate additional TJ services, please submit your request via support@switch.tj.",
  "8. Personal Data and Privacy",
  "To deliver our services, TJ needs to store and process certain personal data. By signing this agreement, you consent to this processing. TJ is committed to protecting your privacy and will never sell your data to third parties.",
  "9. Marketing and Communication",
  "From time to time, TJ may contact you about new products, services, or information that could benefit your business.",
  "By agreeing to our terms of use, you are opting in to receive such communications - every such communication we send you includes an option to unsubscribe at any time.",
  "10. Standard Terms of Use and Intellectual Property",
  "You may not copy, reverse engineer, or decompile any of Transaction Junction's software, methods, or systems. You must comply with these terms as well as any terms of use or conditions shown on the TJ online portal. If you intentionally breach these terms or act in a way that causes TJ to suffer any loss or liability, you will be responsible for covering that loss.",
  "11. Liability",
  "By using our services, you agree that TJ is not responsible for any issues or losses that may arise from their use.",
  "12. Fees and Payment Terms",
  "Fees associated with services will be clearly defined and agreed in writing prior to each service being enabled.",
  "You must sign a debit order mandate authorizing TJ to debit your nominated bank account for all applicable fees.",
  "Monthly and transactional fees will be invoiced in arrears during the first week of each month and debited 30 days later.",
  "TJ will provide detailed invoices for all charges.",
  "Fee disputes should be submitted in writing to accounts@switch.tj.",
  "TJ may apply a CPI-related fee increase annually on June 1st.",
];

export function isTermsHeading(line: string): boolean {
  return /^(Introduction|Definitions:|Your Responsibilities|Transaction Junction's Responsibilities|\d+\.)/.test(line);
}
